import type { NextPage } from 'next';
import Head from 'next/head';

import Slider from '../components/Slider';
import PromoCategories from '../components/PromoCategories';
import Carousel from '../components/common/Carousel';

import { mockCarouselData } from '../mocks/mockCarouselData';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Comfy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/favicon.ico" />
      </Head>

      <Slider />
      <PromoCategories header="Скидки до -40%" />
      <PromoCategories header="Холодильники" />
      <PromoCategories header="Смартфоны" />
      <PromoCategories header="Ноутбуки" />
      <PromoCategories header="Стиральны машины" />
      <PromoCategories header="Игровые консоли" />
      <PromoCategories header="Просмотренные товары" />
      <Carousel display="normal" header="Хиты продаж" items={mockCarouselData.items} />
    </>
  );
};

export default Home;
